URL_SERVICE = "https://4dec1712-862c-445b-98dc-c1dc8c85d0f3.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
LOG_MAIN_PATH = "/api/logs/main/"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
